import React from 'react';
import { ArrowLeft, ReceiptText } from 'lucide-react';

type PolicySection = { title: string; paragraphs?: string[]; bullets?: string[]; after?: string[] };

const sections: PolicySection[] = [
  { title: '1. Subscription Purchases', paragraphs: ['Syncfyre subscriptions may be offered on:'], bullets: ['monthly', 'quarterly', 'half-yearly', 'annual', 'multi-year', 'custom contractual plans'], after: ['The applicable subscription period and price will be communicated before purchase.'] },
  { title: '2. Cancellation', paragraphs: ['Customers may request cancellation of future subscription renewal by contacting Syncfyre through the prescribed account, billing, or support channel.', 'Cancellation generally prevents the next renewal.', 'Unless a refund is otherwise approved under this Policy, cancellation does not result in a prorated refund for the unused portion of an already active subscription.', 'Access may continue until the end of the paid subscription period.'] },
  { title: '3. Non-Refundable Payments', paragraphs: ['Except where required by law or expressly stated otherwise, the following are generally non-refundable once delivered, activated, commenced, consumed, provisioned, or incurred:'], bullets: ['subscription fees for an activated billing period', 'onboarding fees', 'implementation fees', 'setup fees', 'custom configuration charges', 'data migration fees', 'training fees already delivered', 'custom-development fees', 'integration charges', 'API setup charges', 'messaging credits already consumed', 'WhatsApp charges', 'SMS charges', 'email credits', 'payment gateway charges', 'third-party service charges', 'hardware', 'installation charges', 'travel or on-site service expenses', 'domain or externally purchased service fees', 'taxes already remitted where legally non-refundable'] },
  { title: '4. Eligible Refund Circumstances', paragraphs: ['A refund may be considered where:'], bullets: ['you were charged more than once for the same Syncfyre subscription due to a verified duplicate transaction', 'payment was successfully collected but the purchased subscription could not be provisioned because of a failure attributable to Syncfyre', 'a paid service materially differs from the service specifically agreed upon and we are unable to correct the deficiency within a reasonable period', 'a refund is required under applicable consumer law', 'Synckraft expressly approves the refund in writing'], after: ['Under India’s Consumer Protection (E-Commerce) Rules, applicable entities cannot refuse refunds in certain circumstances involving deficient services or services not matching advertised or agreed characteristics. Any mandatory consumer protection obligation will prevail over this Policy.'] },
  { title: '5. Change of Mind', paragraphs: ['Unless expressly offered under a particular promotion, quotation, order form, or subscription plan, Syncfyre does not provide refunds merely because:'], bullets: ['the Customer changes its mind', 'the Customer stops operating its business', 'staff members do not use the software', 'the Customer fails to complete onboarding', 'the Customer does not use available features', 'the Customer finds an alternative software provider', 'the Customer no longer requires the service'], after: ['This provision remains subject to mandatory consumer rights.'] },
  { title: '6. Free Trials and Demonstrations', paragraphs: ['Where a free trial or demonstration is available, customers are encouraged to assess Syncfyre before purchasing.', 'Features demonstrated during a sales presentation may depend on:'], bullets: ['the purchased plan', 'integrations', 'configuration', 'business category', 'additional modules', 'third-party services'], after: ['A demonstration does not automatically entitle a customer to functionality outside the purchased plan.'] },
  { title: '7. Promotional Purchases', paragraphs: ['Discounted, promotional, special-offer, bundled, introductory, or campaign-based subscriptions are generally non-refundable after activation unless:'], bullets: ['the promotional terms expressly provide otherwise', 'the service is materially deficient', 'the refund is required by law'] },
  { title: '8. Subscription Downgrades', paragraphs: ['A downgrade generally applies from the next billing cycle unless otherwise agreed.', 'Unused capacity under a higher plan does not ordinarily generate a refund or credit.'] },
  { title: '9. Upgrades', paragraphs: ['Where a customer upgrades to a higher plan, any adjustment, prorating, credit, or additional charge will be determined according to the applicable quotation, subscription configuration, or billing arrangement.'] },
  { title: '10. Third-Party Charges', paragraphs: ['Certain services depend on third parties.', 'Charges imposed by:'], bullets: ['Meta/WhatsApp', 'SMS providers', 'payment gateways', 'cloud providers', 'device vendors', 'email providers', 'third-party integrations'], after: ['may not be recoverable once incurred.', 'Accordingly, even where a Syncfyre refund is approved, third-party charges that cannot be recovered may be excluded where legally permitted.'] },
  { title: '11. Hardware', paragraphs: ['Where hardware is purchased through or in connection with Syncfyre, warranty, replacement, return, and refund eligibility may depend on the hardware manufacturer’s or supplier’s applicable policy.', 'Hardware that has been:'], bullets: ['installed', 'physically damaged', 'altered', 'improperly used', 'opened where applicable', 'configured specifically for the customer'], after: ['may not be eligible for return except where required by law or covered by warranty.'] },
  { title: '12. Custom Development', paragraphs: ['Payments relating to custom software development, custom integrations, reports, workflows, APIs, modules, or implementation work may become non-refundable once the applicable work has commenced.', 'If project-specific refund or milestone provisions appear in a signed quotation, statement of work, or agreement, those terms will prevail.'] },
  { title: '13. How to Request a Refund', paragraphs: ['Refund requests must be submitted to:', 'Billing Email: [BILLING EMAIL]', 'The request should include:'], bullets: ['business name', 'registered account email or phone number', 'invoice number', 'payment transaction/reference number', 'date of payment', 'amount', 'reason for requesting the refund'], after: ['We may request additional information necessary to verify the transaction.'] },
  { title: '14. Review of Requests', paragraphs: ['Refund requests will be assessed against:'], bullets: ['this Policy', 'the subscription purchased', 'services already rendered', 'third-party costs', 'applicable contracts', 'applicable law'], after: ['Submitting a refund request does not itself guarantee approval.'] },
  { title: '15. Approved Refunds', paragraphs: ['Where a refund is approved, it will generally be processed to the original payment method unless another method is legally or operationally necessary.', 'Actual crediting times may depend on:'], bullets: ['banks', 'card networks', 'UPI providers', 'payment gateways', 'financial institutions'] },
  { title: '16. Chargebacks', paragraphs: ['Customers are encouraged to contact Syncfyre Billing Support before initiating a chargeback so that genuine billing issues can be investigated.', 'Fraudulent or abusive chargebacks may lead to account suspension and recovery proceedings where permitted by law.', 'Nothing in this section prevents customers from exercising legitimate rights available through their bank, payment provider, or applicable law.'] },
  { title: '17. Service Suspension for Payment Default', paragraphs: ['Failure to pay outstanding fees may result in:'], bullets: ['restricted account functionality', 'temporary suspension', 'termination', 'discontinuation of paid integrations'], after: ['Payment of overdue amounts does not automatically entitle the Customer to reimbursement for the period of suspension.'] },
  { title: '18. Account Closure and Data', paragraphs: ['Cancellation or refund does not necessarily result in immediate deletion of Customer Data.', 'Data will be handled according to the Syncfyre Privacy Policy, applicable contractual obligations, retention requirements, backup processes, and applicable law.', 'Customers should export important information before their subscription expires.'] },
  { title: '19. Exceptional Cases', paragraphs: ['Synckraft may, at its discretion and without creating an obligation for future cases, provide:'], bullets: ['service credits', 'plan extensions', 'partial refunds', 'replacement services', 'goodwill adjustments'], after: ['Such exceptions do not amend this Policy for other customers.'] },
  { title: '20. Changes to This Policy', paragraphs: ['We may update this Cancellation and Refund Policy to reflect changes in:'], bullets: ['law', 'payment processes', 'subscription models', 'product functionality', 'business operations'], after: ['The latest version will display the revised “Last Updated” date.'] },
  { title: '21. Contact', paragraphs: ['Synckraft Technologies Pvt. Ltd.\nProduct: Syncfyre\nAddress: 414, 4th Floor, Daga Plazzo Biyani Sqaure, opp. Dmart Camp, Amravati, Maharashtra 444602\nBilling Email: admin@synckraft.in\nSupport Email: sales@synckraft\nPhone: 9867799655'] },
];

export const CancellationRefundPolicyPage: React.FC<{ onNavigate: (pageId: string) => void }> = ({ onNavigate }) => (
  <div className="legal-document relative overflow-hidden py-12 sm:py-16 lg:py-20">
    <div className="pointer-events-none absolute inset-x-0 top-0 h-80 bg-[radial-gradient(circle_at_top_right,rgba(225,64,36,0.13),transparent_50%),linear-gradient(180deg,rgba(15,23,42,0.04),transparent)]" />
    <div className="pointer-events-none absolute right-0 top-0 h-80 w-80 rounded-full bg-[#e14024]/10 blur-3xl" />
    <div className="legal-document-wrap mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
      <button onClick={() => onNavigate('home')} className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-slate-600 transition-colors hover:text-[#e14024]"><ArrowLeft className="h-4 w-4" /> Back to Home</button>
      <header className="legal-document-header relative mb-10 overflow-hidden rounded-[2rem] px-6 py-10 sm:px-10 sm:py-14"><div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-[#e14024]/30 blur-3xl" /><div className="absolute bottom-0 right-0 h-48 w-48 translate-x-1/3 translate-y-1/3 rounded-full border-[28px] border-[#e14024]/20" /><div className="relative"><div className="mb-6 flex items-center justify-between gap-4"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.2em] text-orange-200"><ReceiptText className="h-4 w-4" /> Legal</div><span className="hidden text-xs font-bold uppercase tracking-[0.18em] text-slate-400 sm:block">Billing &amp; access</span></div><h1 className="max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Cancellation and Refund Policy</h1><p className="mt-4 max-w-2xl text-base text-slate-300 sm:text-lg">Syncfyre — Powered by Synckraft Technologies Pvt. Ltd.</p><div className="mt-8 flex flex-col gap-2 border-t border-white/10 pt-5 text-sm text-slate-300 sm:flex-row sm:gap-8"><span><strong className="text-white">Last Updated:</strong> 27 August 2026</span><span><strong className="text-white">Effective Date:</strong> 27 August 2026</span></div></div></header>
      <div className="mb-10 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[#e14024]/20 bg-[#fff4f1] p-5"><div className="text-xs font-black uppercase tracking-[0.18em] text-[#c83218]">Before you cancel</div><p className="mt-2 text-sm leading-7 text-slate-700">Cancellation generally prevents the next renewal. Access may continue through the end of the paid subscription period.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">Need billing help?</div><p className="mt-2 text-sm leading-7 text-slate-700">Use the contact details in Section 21 for refund requests, billing questions, or support.</p></div></div>
      <div className="grid items-start gap-8 lg:grid-cols-[180px_minmax(0,1fr)] lg:gap-10"><aside className="hidden lg:block lg:sticky lg:top-24"><div className="border-l-2 border-slate-200 pl-4"><div className="mb-4 text-xs font-black uppercase tracking-[0.18em] text-slate-400">On this page</div><nav className="space-y-2">{sections.map((section) => <a key={section.title} href={`#${section.title.split('. ')[0]}`} className="block text-xs font-semibold leading-5 text-slate-500 transition-colors hover:text-[#e14024]">{section.title}</a>)}</nav></div></aside>
      <article className="legal-document-body rounded-3xl px-5 py-8 sm:px-10 sm:py-12"><div className="legal-prose prose prose-slate max-w-none prose-p:leading-8 prose-li:my-1 prose-headings:scroll-mt-24 prose-headings:font-black prose-h2:mt-12 prose-h2:border-t prose-h2:border-slate-100 prose-h2:pt-8 prose-h2:text-2xl"><p>This Cancellation and Refund Policy explains when payments made for Syncfyre products and services may be cancelled or refunded.</p><p>Nothing in this Policy limits statutory consumer rights that cannot lawfully be waived.</p>{sections.map((section) => <section key={section.title} id={section.title.split('. ')[0]}><h2>{section.title}</h2>{section.paragraphs?.map((p) => <p key={p} className={p.includes('\n') ? 'whitespace-pre-line' : undefined}>{p}</p>)}{section.bullets && <ul>{section.bullets.map((item) => <li key={item}>{item};</li>)}</ul>}{section.after?.map((p) => <p key={p}>{p}</p>)}</section>)}</div></article></div>
    </div>
  </div>
);