import React from 'react';
import { ArrowLeft, FileCheck2 } from 'lucide-react';

type TermsSection = { title: string; paragraphs?: string[]; bullets?: string[]; after?: string[] };

const sections: TermsSection[] = [
  { title: '1. About Syncfyre', paragraphs: ['Syncfyre is a cloud-based business management and automation platform that may provide features including, depending on the subscribed plan:'], bullets: ['Customer Relationship Management (CRM)', 'Lead and sales management', 'Membership management', 'Customer and member records', 'Employee and trainer management', 'Attendance management', 'Appointments and scheduling', 'Billing and invoicing', 'Payment tracking', 'Point-of-Sale functionality', 'Inventory management', 'Expense and income tracking', 'Marketing tools', 'WhatsApp and communication automation', 'Notifications and reminders', 'Loyalty and retention tools', 'Reports and analytics', 'Business intelligence', 'Multi-location management', 'Workflow automation', 'Integrations with third-party services', 'AI-powered features', 'Industry-specific business modules'], after: ['Certain features may differ according to industry, subscription plan, geographical region, integration availability, or product version.'] },
  { title: '2. Eligibility', paragraphs: ['You must be legally capable of entering into a binding contract under applicable law.', 'Where an organization creates an account, the organization is responsible for all activities carried out through its administrators, employees, trainers, managers, franchisees, representatives, contractors, and other authorized users.'] },
  { title: '3. Account Registration', paragraphs: ['You agree to provide accurate, complete, and current information while registering.', 'You are responsible for:'], bullets: ['keeping login credentials secure', 'maintaining appropriate user access permissions', 'ensuring that only authorized individuals use your account', 'promptly disabling access for former employees or unauthorized persons', 'notifying us of suspected unauthorized access'], after: ['You are responsible for activities conducted using your account unless such activities result directly from a security failure attributable to Synckraft.'] },
  { title: '4. Subscription and Licensing', paragraphs: ['Syncfyre is generally provided on a subscription or licensed-access basis.', 'Unless otherwise agreed in writing, purchasing a Syncfyre subscription grants you a limited, non-exclusive, non-transferable, revocable right to use the subscribed services during the subscription period.', 'You do not acquire ownership of the Syncfyre software, source code, infrastructure, algorithms, designs, trademarks, intellectual property, or underlying technology.', 'Subscription limits may apply to:'], bullets: ['users', 'branches', 'locations', 'members', 'contacts', 'messages', 'automation runs', 'storage', 'API calls', 'integrations', 'reports', 'transactions', 'specific functionality'] },
  { title: '5. Fees and Payment', paragraphs: ['Applicable subscription fees, implementation fees, onboarding fees, integration charges, hardware charges, add-on charges, messaging charges, taxes, and other fees will be communicated at the time of purchase or through an applicable quotation, order form, invoice, or plan page.', 'Unless expressly stated otherwise:'], bullets: ['prices are exclusive of applicable taxes', 'payments must be made within the invoiced period', 'subscription fees may be charged in advance', 'delayed payments may result in suspension of services', 'third-party charges may be billed separately', 'fees may vary when a customer upgrades, adds branches, increases usage, or purchases additional services'], after: ['We may revise pricing for future subscription periods by giving reasonable notice where practicable.'] },
  { title: '6. Automatic Renewal', paragraphs: ['Where a plan is configured for automatic renewal, it may renew at the end of the subscription term unless cancelled before the applicable renewal date.', 'Where automatic payment is enabled, you authorize the applicable payment provider to process renewal charges in accordance with the selected plan.'] },
  { title: '7. Customer Data', paragraphs: ['“Customer Data” means information uploaded, entered, collected, imported, transmitted, generated, or otherwise processed through Syncfyre by or on behalf of a customer.', 'Customer Data may include:'], bullets: ['customer/member details', 'phone numbers', 'email addresses', 'addresses', 'membership information', 'attendance information', 'transaction records', 'invoices', 'payment records', 'employee data', 'trainer data', 'lead information', 'appointment data', 'communication history', 'business records', 'uploaded documents', 'profile photographs', 'biometric-device identifiers or attendance records where integrated', 'reports and analytics data'], after: ['As between Synckraft and the Customer, the Customer retains its rights in Customer Data.', 'The Customer grants Synckraft the limited rights necessary to host, process, transmit, back up, analyse, and otherwise handle Customer Data for the purpose of providing, securing, maintaining, supporting, and improving the Services, subject to applicable law and our Privacy Policy.'] },
  { title: '8. Customer Responsibility for Personal Data', paragraphs: ['Businesses using Syncfyre may collect personal data relating to their customers, members, patients, employees, trainers, leads, vendors, or other individuals.', 'The Customer is responsible for ensuring that it has an appropriate legal basis, permission, consent, notice, or authorization required to collect and use such information and to provide it to Syncfyre.', 'You must not use Syncfyre to unlawfully collect, process, disclose, sell, exploit, or communicate personal data.'] },
  { title: '9. Messaging, WhatsApp, SMS and Email', paragraphs: ['Syncfyre may enable businesses to send messages through WhatsApp, SMS, email, push notifications, or other communication channels.', 'You are solely responsible for:'], bullets: ['obtaining required customer consents or opt-ins', 'maintaining evidence of consent where required', 'respecting opt-out and unsubscribe requests', 'complying with applicable anti-spam, telecommunication, WhatsApp, Meta, email, and marketing rules', 'ensuring that marketing communications are lawful and not deceptive'], after: ['Use of third-party messaging platforms is also subject to their respective terms, policies, pricing, technical limitations, and account restrictions.', 'Syncfyre does not guarantee the delivery of every message.'] },
  { title: '10. Third-Party Integrations', paragraphs: ['Syncfyre may integrate with services including:'], bullets: ['payment gateways', 'WhatsApp providers', 'Meta services', 'SMS providers', 'email providers', 'biometric devices', 'accounting software', 'analytics services', 'cloud platforms', 'APIs', 'calendars', 'access-control systems', 'other third-party applications'], after: ['Third-party services are governed by their own terms and privacy policies.', 'Synckraft is not responsible for outages, restrictions, changes, suspensions, data practices, fees, or failures caused by third-party service providers.'] },
  { title: '11. Payment Processing', paragraphs: ['Where payments are collected using third-party payment gateways, the payment transaction may be processed directly by the relevant payment provider.', 'Unless expressly stated otherwise, Synckraft does not store complete payment card details.', 'Payment failures, chargebacks, settlement delays, payment gateway disputes, or banking errors may be governed by the policies of the applicable payment provider or financial institution.'] },
  { title: '12. Artificial Intelligence Features', paragraphs: ['Some Syncfyre functions may use artificial intelligence, machine learning, statistical models, automation, or third-party AI systems.', 'AI-generated:'], bullets: ['recommendations', 'summaries', 'classifications', 'forecasts', 'marketing content', 'responses', 'reports', 'insights'], after: ['may contain errors or inaccuracies.', 'AI output must be reviewed by the Customer before being relied upon for material commercial, financial, medical, employment, legal, or operational decisions.'] },
  { title: '13. Acceptable Use', paragraphs: ['You must not:'], bullets: ['use Syncfyre for unlawful activities', 'upload malicious software or harmful code', 'attempt unauthorized system access', 'probe, scan, or test vulnerabilities without permission', 'reverse engineer the software except where expressly permitted by law', 'interfere with platform operation', 'circumvent subscription or usage restrictions', 'scrape the platform without authorization', 'resell access unless authorized under a written partner agreement', 'impersonate another person', 'process stolen or unlawfully obtained personal data', 'send spam or prohibited communications', 'use the platform to defraud consumers', 'infringe intellectual property rights', 'use Syncfyre in violation of applicable law'], after: ['We may suspend or terminate accounts involved in prohibited activity.'] },
  { title: '14. Business Decisions and Records', paragraphs: ['Syncfyre is a software tool and does not replace professional:'], bullets: ['accounting', 'tax', 'legal', 'financial', 'medical', 'compliance', 'HR', 'business advice'], after: ['Customers remain responsible for verifying invoices, accounts, tax calculations, payments, employee records, attendance records, financial reports, statutory obligations, and other business information generated or stored through the platform.'] },
  { title: '15. Hardware and Biometric Integrations', paragraphs: ['Where Syncfyre integrates with biometric, facial recognition, fingerprint, RFID, QR, access-control, or attendance hardware, performance may depend on third-party devices, networks, local software, middleware, drivers, and hardware configuration.', 'Customers are responsible for obtaining any legally required consent before collecting or processing biometric or similar sensitive information.'] },
  { title: '16. Availability and Maintenance', paragraphs: ['We aim to maintain reliable availability but do not guarantee uninterrupted operation.', 'The Service may occasionally be unavailable because of:'], bullets: ['scheduled maintenance', 'emergency maintenance', 'security incidents', 'network failure', 'hosting provider outages', 'third-party failures', 'internet disruption', 'force majeure', 'product upgrades'], after: ['Where reasonably possible, we may provide advance notice of planned significant maintenance.'] },
  { title: '17. Backups and Data Export', paragraphs: ['We may maintain backups for operational continuity.', 'However, customers are encouraged to periodically export important business records.', 'Data export capabilities may depend on subscription plan, record type, technical feasibility, security requirements, or contractual arrangements.'] },
  { title: '18. Suspension', paragraphs: ['We may suspend access where reasonably necessary because of:'], bullets: ['non-payment', 'security risk', 'fraudulent activity', 'unlawful use', 'material breach of these Terms', 'abusive usage', 'threat to platform infrastructure', 'legal or regulatory requirements'], after: ['Where appropriate, we will attempt to provide notice and an opportunity to resolve the issue.'] },
  { title: '19. Termination', paragraphs: ['You may discontinue Syncfyre according to the cancellation terms applicable to your subscription.', 'We may terminate an account where there is:'], bullets: ['material breach of these Terms', 'repeated non-payment', 'unlawful conduct', 'abuse of our systems', 'fraud', 'security threats', 'legal necessity'], after: ['Termination does not automatically create a refund entitlement.'] },
  { title: '20. Data Following Termination', paragraphs: ['Following account termination or subscription expiry, we may retain Customer Data for a limited period for legitimate operational, legal, backup, fraud-prevention, dispute-resolution, or compliance purposes.', 'After applicable retention periods expire, Customer Data may be deleted or anonymized unless retention is required by law.', 'Customers should export required data before account closure.'] },
  { title: '21. Intellectual Property', paragraphs: ['Syncfyre and all related:'], bullets: ['software', 'trademarks', 'logos', 'interfaces', 'dashboards', 'workflows', 'documentation', 'databases', 'graphics', 'designs', 'source code', 'APIs', 'algorithms', 'models', 'product architecture', 'marketing material'], after: ['are owned by or licensed to Synckraft Technologies Pvt. Ltd.', 'No ownership rights are transferred to users.'] },
  { title: '22. Feedback', paragraphs: ['If you voluntarily provide ideas, suggestions, product feedback, or improvement recommendations, we may use such feedback to improve our products without an obligation to compensate you, provided we do not disclose your confidential information in doing so.'] },
  { title: '23. Confidentiality', paragraphs: ['Each party should protect confidential business, technical, financial, customer, pricing, and operational information received from the other party.', 'Confidential information may be disclosed where required by law, court order, regulatory authority, or with the owner’s authorization.'] },
  { title: '24. Disclaimer of Warranties', paragraphs: ['To the extent permitted by law, Syncfyre is provided on an “as available” basis.', 'We do not warrant that:'], bullets: ['the Service will always operate without interruption', 'all software will be error-free', 'all third-party integrations will remain available', 'every communication will be delivered', 'all reports will always be accurate if underlying data is inaccurate', 'use of Syncfyre alone will increase revenue, retention, profitability, or business performance'], after: ['Nothing in these Terms excludes warranties or rights that cannot lawfully be excluded.'] },
  { title: '25. Limitation of Liability', paragraphs: ['To the maximum extent permitted by applicable law, Synckraft Technologies Pvt. Ltd. will not be liable for indirect, incidental, special, punitive, or consequential losses, including loss of profits, goodwill, opportunities, business interruption, or data, arising from the use of Syncfyre.', 'Where liability cannot legally be excluded, our aggregate contractual liability should, subject to applicable law and the applicable commercial agreement, be limited to the fees paid by the Customer for the affected Syncfyre services during the preceding twelve months.', 'This limitation does not apply where liability cannot lawfully be limited.'] },
  { title: '26. Indemnification', paragraphs: ['To the extent permitted by law, you agree to indemnify Synckraft Technologies Pvt. Ltd. against third-party claims arising from:'], bullets: ['your unlawful use of Syncfyre', 'unlawful Customer Data', 'unauthorized marketing communications', 'violation of third-party rights', 'violation of applicable law', 'misuse by your authorized users'] },
  { title: '27. Consumer Rights', paragraphs: ['Nothing in these Terms is intended to remove statutory rights available to consumers under applicable law.', 'Where mandatory consumer law conflicts with these Terms, mandatory law will prevail.'] },
  { title: '28. Changes to the Service', paragraphs: ['We may improve, modify, replace, add, discontinue, or reorganize functionality from time to time.', 'Material changes that significantly affect paid functionality may be communicated where reasonably practicable.'] },
  { title: '29. Amendments to These Terms', paragraphs: ['We may update these Terms to reflect product, operational, legal, regulatory, security, or commercial changes.', 'The updated version will display a revised “Last Updated” date.', 'Continued use after an updated version becomes effective may constitute acceptance where legally permitted.'] },
  { title: '30. Governing Law and Jurisdiction', paragraphs: ['These Terms shall be governed by the laws of India.', 'Subject to applicable consumer law and any mandatory jurisdiction requirements, disputes shall be subject to the exclusive jurisdiction of competent courts at [INSERT CITY AND STATE OF REGISTERED/PRINCIPAL OFFICE], India.'] },
  { title: '31. Grievance and Contact Information', paragraphs: ['For questions, complaints, legal notices, or support relating to these Terms, contact:', 'Synckraft Technologies Pvt. Ltd.\nProduct: Syncfyre\nAddress: 414, 4th Floor, Daga Plazzo Biyani Sqaure, opp. Dmart Camp, Amravati, Maharashtra 444602\nEmail: admin@synckraft.in\nSupport Email: Sales@synckraft.in\nPhone: 9867799655'] },
  { title: '32. Entire Agreement', paragraphs: ['These Terms, together with the Privacy Policy, Refund Policy, applicable quotation, order form, subscription plan, and any written enterprise agreement constitute the agreement governing use of Syncfyre.', 'If a separately executed agreement conflicts with these general Terms, the separately executed agreement will prevail to the extent of that conflict.'] },
];

export const TermsAndConditionsPage: React.FC<{ onNavigate: (pageId: string) => void }> = ({ onNavigate }) => (
  <div className="legal-document relative overflow-hidden py-12 sm:py-16 lg:py-20">
    <div className="pointer-events-none absolute right-0 top-0 h-80 w-80 rounded-full bg-[#e14024]/10 blur-3xl" />
    <div className="legal-document-wrap mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
      <button onClick={() => onNavigate('home')} className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-slate-600 transition-colors hover:text-[#e14024]"><ArrowLeft className="h-4 w-4" /> Back to Home</button>
      <header className="legal-document-header relative mb-12 overflow-hidden rounded-3xl px-6 py-10 sm:px-10 sm:py-14">
        <div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-[#e14024]/30 blur-3xl" />
        <div className="relative"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.2em] text-orange-200"><FileCheck2 className="h-4 w-4" /> Legal</div><h1 className="text-4xl font-black tracking-tight sm:text-6xl">Terms and Conditions</h1><p className="mt-4 text-base text-slate-300 sm:text-lg">Syncfyre — Powered by Synckraft Technologies Pvt. Ltd.</p><div className="mt-8 flex flex-col gap-2 text-sm text-slate-300 sm:flex-row sm:gap-8"><span><strong className="text-white">Last Updated:</strong> 27 August 2026</span><span><strong className="text-white">Effective Date:</strong> 27 August 2026</span></div></div>
      </header>
      <article className="legal-document-body rounded-3xl px-5 py-8 sm:px-10 sm:py-12"><div className="legal-prose prose prose-slate max-w-none prose-p:leading-8 prose-li:my-1 prose-headings:scroll-mt-24 prose-headings:font-black prose-h2:mt-12 prose-h2:border-t prose-h2:border-slate-100 prose-h2:pt-8 prose-h2:text-2xl"> <p>These Terms and Conditions (“Terms”) govern access to and use of Syncfyre, a software platform owned, operated, and provided by Synckraft Technologies Pvt. Ltd. (“Synckraft”, “Syncfyre”, “we”, “us”, or “our”).</p><p>By registering for, purchasing, accessing, or using Syncfyre, you (“Customer”, “Business”, “User”, “you”, or “your”) agree to be bound by these Terms.</p><p>If you are accepting these Terms on behalf of a company, gym, salon, clinic, restaurant, retail store, institution, franchise, or another organization, you represent that you have authority to bind that organization to these Terms.</p>{sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs?.map((p) => <p key={p} className={p.includes('\n') ? 'whitespace-pre-line' : undefined}>{p}</p>)}{section.bullets && <ul>{section.bullets.map((item) => <li key={item}>{item};</li>)}</ul>}{section.after?.map((p) => <p key={p}>{p}</p>)}</section>)}</div></article>
    </div>
  </div>
);
